# enable or disable the detector
bool enable

# for BASELINE_PAIR, distance between a pair of detections (typically reflectors) that form the pattern
float64 baseline

# for ALVAR, id of the tag, or id of the master tag in bundles, use -1 for all
int32 alvar_marker_id

# for VERTICAL_CYLINDER, requested cylinder diameter [m] when enabling
float64 diameter

# for COLOR_IN_ROI, requested target color
target_detector/Color color

---

bool success
