# enable or disable the detector
bool enable

# for TYPE_BASELINE_PAIR, distance between a pair of detections (typically reflectors) that form the pattern
float64 baseline

# for TYPE_ALVAR, id of the tag, or id of the master tag in bundles, use -1 for all
int32 alvar_marker_id

---

bool success
