small_reflectors: # same as node namespace
  enabled_by_default: false
  vizbose: false
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  min_reflector_intensity: 250
  reflector_size: 0.04
  max_detection_range: 20

big_reflectors:
  enabled_by_default: true
  vizbose: false
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  min_reflector_intensity: 250
  reflector_size: 0.06
  max_detection_range: 50

docking_pairs:
  vizbose: false
  baseline_tolerance: 0.03