small_reflectors: # same as node namespace
  type: reflector # type here is only informative, but should be in consonance with node in launch, i.e.: reflector_perceptor type
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  scan_type: "sensor_msgs/LaserScan" # "sensor_msgs/LaserScan" or "sick_safetyscanners/ExtendedLaserScanMsg"
  min_reflector_intensity: 250 # only used for "sensor_msgs/LaserScan"
  reflector_size: 0.04
  max_detection_range: 20
  scan_decimation: 5 # only every N-th scan is processed. Decimation = 3 -> process scan 1, skip scans 2 and 3, process scan 4, ...

big_reflectors:
  type: reflector
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  scan_type: "sensor_msgs/LaserScan" # "sensor_msgs/LaserScan" or "sick_safetyscanners/ExtendedLaserScanMsg"
  min_reflector_intensity: 250 # only used for "sensor_msgs/LaserScan"
  reflector_size: 0.06
  max_detection_range: 50
  scan_decimation: 5

alvars:
  type: alvar
  enabled_by_default: true # bundle processing by ar_track_alvar is enabled/disabled accordingly
  vizbose: true
  robot_frame: "platform"

beacons:
  type: tmk_uwb
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"

vertical_cylinders:
  type: vertical_cylinder
  enabled_by_default: false
  vizbose: true
  robot_frame: "platform"
  source_name: "camera"
  diameter: 1.0
  min_cloud_points: 1000
  crop_min: [-1.25, 0.2, 0.5]
  crop_max: [1.25, 1.0, 4.0]
  voxel_size: [0.02, 0.02, 0.02]
