small_reflectors: # same as node namespace
  type: reflector # type here is only informative, but should be in consonance with node in launch, i.e.: reflector_perceptor type
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  scan_type: "sensor_msgs/LaserScan" # or "sick_safetyscanners/ExtendedLaserScanMsg"
  min_reflector_intensity: 250
  reflector_size: 0.04
  max_detection_range: 20
  scan_decimation: 5.0 # only every N-th scan is processed. Decimation = 3 -> process scan 1, skipp scans 2, 3, process scan 4, ...

big_reflectors:
  type: reflector
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"
  lidars: ["lidar_front", "lidar_back"]
  scan_type: "sensor_msgs/LaserScan" # or "sick_safetyscanners/ExtendedLaserScanMsg"
  min_reflector_intensity: 250
  reflector_size: 0.06
  max_detection_range: 50
  scan_decimation: 5.0

alvars:
  type: alvar
  enabled_by_default: true # bundle processing by ar_track_alvar is enabled/disabled accordingly
  vizbose: true
  robot_frame: "platform"

beacons:
  type: tmk_uwb
  enabled_by_default: true
  vizbose: true
  robot_frame: "platform"
